// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3q7nOHDrk_-F7eUUrjU3wtPU1D6DIaDA',
    appId: '1:510072287638:android:e9d7aaa298c7c2076f2db7',
    messagingSenderId: '510072287638',
    projectId: 'zolane-50c21',
    storageBucket: 'zolane-50c21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzVoS3h2rnuZqe1xS-wpg6elnEOXJHgw8',
    appId: '1:510072287638:ios:28dd8b416c6a355b6f2db7',
    messagingSenderId: '510072287638',
    projectId: 'zolane-50c21',
    storageBucket: 'zolane-50c21.firebasestorage.app',
    iosBundleId: 'com.zolane.zolane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzVoS3h2rnuZqe1xS-wpg6elnEOXJHgw8',
    appId: '1:510072287638:ios:28dd8b416c6a355b6f2db7',
    messagingSenderId: '510072287638',
    projectId: 'zolane-50c21',
    storageBucket: 'zolane-50c21.firebasestorage.app',
    iosBundleId: 'com.zolane.zolane',
  );
}
